### ISSUE TITLE
Dev server hangs & jest tests won't run, then server times out

### ISSUE THREAD

**Issue by nicklevenson** [argos-ci/jest-puppeteer#502] opened 2022-11-07 19:47 UTC
## 🐛 Bug Report

Server runs, but tests never get called & server hangs up. 

## To Reproduce

in Package.json:

`"integration": "ESLINT_NO_DEV_ERRORS=true jest -c src/tests/integration/jest.config.js"`
```node v18.6.0```
```
    "jest-puppeteer": "^8.0.5",
    "puppeteer": "^19.7.5"
```

In jest config `src/tests/integration/test.config.js`:
```
  module.exports = {
  preset: "jest-puppeteer",
  testRegex: './*\\.test\\.js$'
};
```

In `jest-puppeteer.config.js`: 
```module.exports = {
  server: {
    command: 'npm run start',
    port: 3000,
    launchTimeout: 10000,
    debug: true
  },
  launch: {
    dumpio: true,
    headless: false,
    product: 'chrome',
  },
  browserContext: 'default',
}
```
Using an M1 on Monterey 12.0.1

## Expected behavior
- running `npm run integration`
- Server should start, tests should run

Paste the results here:

```
Jest dev-server output:
[Jest Dev server] 
> client@0.1.0 start
> ESLINT_NO_DEV_ERRORS=true react-scripts start
... compiling stuff
webpack compiled with 28 warnings
Server has taken more than 10000ms to start.
```

**Comment by gregberge** [comment] 2023-03-17 08:56
Are you sure that the specified port is correct? I think it is a configuration issue nothing more.

**Comment by nicklevenson** [comment] 2023-03-17 14:57
> Are you sure that the specified port is correct? I think it is a configuration issue nothing more.

My apologies, the posted config was a bit outdated. This is what I've been using. I should also note I'm using create-react-app. I noticed the example in the readme for CRA isn't available anymore - perhaps related?

My server starts on the specified port and looks fine, the launcher just doesn't recognize it has started up

```
module.exports = {
  server: {
    command: 'PORT=3333 npm run start',
    port: 3333,
    launchTimeout: 10000
  },
  launch: {
    headless: process.env.HEADLESS !== 'false',
    product: 'chrome',
  },
  browserContext: 'default',
}
```

**Comment by gregberge** [comment] 2023-04-01 15:10
Hmm it is weird.

**Comment by ohcibi** [comment] 2023-05-06 21:48
I can confirm the issue using puppeteer-20.1.1 and jest-puppeteer-8.0.6

The development server behaves as OP describes. It'll get started and takes connections. Also manually testing with `wait-on` shows that the port became available once that server hast started.

Jest-puppeteer/jest/puppeteer or whatever is not recognizing it though.

The spawned server is also not killed properly because of that.

Also `usedPortAction` is ignored. Only thing that happens when the port is in use, it is telling me that the port is in use and then exits.

Steps to reproduce:

1. create react app
2. setup puppeteer and jest-puppeteer according to this documentation and enable automatic server starting
3. run it

**Comment by gregberge** [comment] 2023-05-24 20:27
I think it is fixed in the new version by the change on port detection.

**Closed by gregberge** 2023-05-24 20:27 UTC
