### ISSUE TITLE
expect-puppeteer: TypeError: expect(...).toMatchElement is not a function

### ISSUE THREAD

**Issue by azizur** [argos-ci/jest-puppeteer#497] opened 2022-10-18 12:59 UTC
## 🐛 Bug Report

When upgraded to [v6.1.1](https://github.com/smooth-code/jest-puppeteer/releases/tag/v6.1.1) from [v5.0.4](https://github.com/smooth-code/jest-puppeteer/releases/tag/v5.0.4) I am getting the following errors.

```
TypeError: expect(...).toMatchElement is not a function
```

```
TypeError: expect(...).toFill is not a function
```

```
TypeError: expect(...).toClick is not a function
```

## To Reproduce

Steps to reproduce the behaviour:
* switch from v5.0.4 to v6.1.1

## Expected behavior

Existing behaviour should not break and the aforementioned functions to exist on the `expect` object.

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 12.6
 - CPU: (10) arm64 Apple M1 Max
 - Memory: 3.71 GB / 32.00 GB
 - Shell: 5.8.1 - /bin/zsh
## Binaries:
 - Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
 - npm: 8.19.2 - ~/projects/mahabba/client/node_modules/.bin/npm
## npmPackages:
 - jest-puppeteer: 6.1.1 => 6.1.1
```

**Comment by azizur** [comment] 2022-10-18 13:11
Reverting to [v5.0.4](https://github.com/smooth-code/jest-puppeteer/releases/tag/v5.0.4) fixes the issue.

**Comment by UziTech** [comment] 2022-10-19 07:38
The types are provided by [@types/jest-environment-puppeteer](https://www.npmjs.com/package/@types/jest-environment-puppeteer) It would be better to try to create an issue there to get this fixed.

**Comment by grzegorz-zadora** [comment] 2022-11-11 12:43
Please re-open this. `TypeError` is not related to TypeScript. It's a standard JS error: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError

There is some issue with how `expect-puppeteer` is exported. 

It doesn't work, neither with `import "expect-puppeteer";` nor `import expectPuppeteer from "expect-puppeteer";`.

It seems it's somehow related to: https://swc.rs/docs/usage/jest. I'll try to create a small, reproducible example later and get back to you.

**Comment by UziTech** [comment] 2022-11-11 16:54
It looks like something is wrong with the way we add the methods. Most likely jest changed something in the latest major release that broke us.

**Comment by angwonson** [comment] 2023-01-04 01:47
As @mondeja mentions - downgrading puppeteer to 17.1.3 solves the problem. I had installed 19.4.1.

Working:
`
    "jest": "^29.3.1",
    "jest-environment-jsdom": "^29.3.1",
    "jest-environment-node": "^29.3.1",
    "jest-puppeteer": "^6.2.0",
    "puppeteer": "17.1.3",
`

**Comment by shunshimono** [comment] 2023-01-10 17:42
I still have this issue, is it resolved?

**Comment by gregberge** [comment] 2023-02-04 16:09
I close it, please reopen it if you experience the issue.

**Closed by gregberge** 2023-02-04 16:09 UTC

**Comment by fregante** [comment] 2023-03-08 11:13
I think this was fixed for me, thank you!

```diff
- import puppeteer from 'expect-puppeteer';
- const expect = puppeteer.default;
+ import {expect} from 'expect-puppeteer';
```
